# Generated by Django 4.2.19 on 2025-03-14 14:22

from django.db import migrations


def populate_items(apps, schema_editor):
    Item = apps.get_model("zssn", "Item")

    Item.objects.get_or_create(name="Water", points=4)
    Item.objects.get_or_create(name="Food", points=3)
    Item.objects.get_or_create(name="Medication", points=2)
    Item.objects.get_or_create(name="Ammunition", points=1)


class Migration(migrations.Migration):

    dependencies = [
        ("zssn", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_items),
    ]
