# Generated by Django 4.2.19 on 2025-03-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0002_populate_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='date_infected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
