# Generated by Django 4.2.19 on 2025-03-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn', '0003_survivor_date_infected'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('survivor', 'item'), name='unique_survivor_item'),
        ),
    ]
